#!/bin/csh

cat > ./pbs_script << END_OF_PBS_SCRIPT
#PBS -S /bin/csh
#PBS -l nodes=01:ppn=01
#PBS -q small
#PBS -N g03_pbs
#PBS -o LGI_output

setenv LGI_DIR /home/\${USER}/LGI
setenv PRIVATE_KEY_FILE \${LGI_DIR}/certificates/woodcrest.key
setenv REPOSITORY \`\${LGI_DIR}/daemon/bin/xml repository < \${PBS_O_WORKDIR}/LGI_job_specifics\`

setenv LD_LIBRARY_PATH /home/g03/g03d01
setenv g03root /home/g03/g03d01
source /home/g03/g03d01/g03/bsd/g03.login

setenv NODES \`/bin/cat \${PBS_NODEFILE}\`
cd /scratch/\${USER}/\${PBS_JOBID}

setenv CWD \`pwd\`

if ( \${REPOSITORY} != "" ) then
 setenv DATE \`date\`
 echo "G03_PBS started retrieving repository \${REPOSITORY} to \${NODES}:\${CWD} at \${DATE}." 
 scp -qBri \${PRIVATE_KEY_FILE} "\${REPOSITORY}/*" .

 dos2unix -n \${PBS_O_WORKDIR}/LGI_input g03.input

 setenv DATE \`date\`
 echo "G03_PBS started g03 on node \${NODES} at \${DATE}." 
 g03 > g03.output < g03.input

 setenv DATE \`date\`
 echo "G03_PBS started sending back the output from \${NODES}:\${CWD} to repository \${REPOSITORY} at \${DATE}." 
 chmod 664 ./*
 scp -qBri \${PRIVATE_KEY_FILE} ./* \${REPOSITORY}
else
 echo "ERROR: No repository was specified for job... Stopping..."
endif

setenv DATE \`date\`
echo "G03_PBS finished at \${DATE}." 
touch \${PBS_O_WORKDIR}/finished
END_OF_PBS_SCRIPT

qsub pbs_script > ./running
