#!/bin/sh
if [ -f ll_running ]
then
 ID=`cat ll_running`
 FINISHED=`llq $ID  | grep $ID`
 if [ "$FINISHED" == "" ]
 then
  if [ -f aborted ]
  then
   PID=`cat running`
   kill $PID
   touch finished
   rm ll_running
   rm running
   exit 0
  else
   exit 1
  fi
 else
  llcancel $ID
  touch aborted
  exit 1
 fi
else
 if [ -f running ]
 then
  PID=`cat running`
  kill $PID
  touch finished
  rm running
  exit 0
 else
  exit 1
 fi
fi
