#!/bin/sh
export X509_USER_PROXY=./x509_proxy_cert
if [ -f running ]
then
 ID=`cat running`
 FINISHED=`glite-wms-job-status ${ID} | grep "Current Status" | grep -iE "Done|Cancelled|Cleared|Aborted"`
 if [ "$FINISHED" != "" ]
 then
  if [ -f aborted ]
  then
   exit 0
  fi
  if [ -f finished ]
  then
   exit 1
  else
   exit 0 
  fi
 else
  exit 0
 fi
else
 exit 1
fi
