#!/bin/bash

# some settings...
export CERT_PASSWD="m@rks0m3rs007"
export VOMS="ncf"

# check if another job is generating a proxy...
while [ -f /tmp/gLiteProxyLocked_${USER} ]
 do
   sleep 10
 done

# set lock...
touch /tmp/gLiteProxyLocked_${USER}

# register at myproxy px.grid.sara.nl...
echo ${CERT_PASSWD} | myproxy-init -s px.grid.sara.nl -d -n -S > /dev/null

# create new proxy cert for 196 hours...
echo ${CERT_PASSWD} | voms-proxy-init -voms ${VOMS} -valid 196:00 -pwstdin -q &> /dev/null

# delegate it to the wms...
glite-wms-job-delegate-proxy -d ${USER}_hello &> /dev/null

# create job script...
cat > hello.submitted.sh << EOF_SCRIPT
export HOST=\`hostname -f\`
export DATE=\`date\`
export INPUT=\`cat LGI_input\`
echo Hello_World_GLITE from \${HOST} at \${DATE} with input: \${INPUT} ...
EOF_SCRIPT

# create JDL for this job script...
cat > hello.submitted.jdl << EOF_JDL
type = "Job";
jobtype = "Normal";
executable = "/bin/bash";
arguments = "hello.submitted.sh";
stdoutput = "LGI_output";
stderror = "stderr";
outputsandbox = { "LGI_output", "stderr" };
inputsandbox = { "hello.submitted.sh", "LGI_input" };
shallowretrycount = 3;
requirements = ( other.glueceinfototalcpus >= 1 && other.gluecepolicymaxcputime > 30 );
myproxyserver = "px.grid.sara.nl";
EOF_JDL

# create and submit new job from JDL...
glite-wms-job-submit -d ${USER}_hello -o ${HOME}/my-glite-jobs hello.submitted.jdl | grep https | tail -1 &> ./running
export JOB_ID=`cat ./running`

# remove lock...
rm -rf /tmp/gLiteProxyLocked_${USER}

# wait until job is finished, sleep a bit...
export JOB_STATE=""
while [ "${JOB_STATE}" == "" ]
do
    sleep 60
    export JOB_STATE=`glite-wms-job-status ${JOB_ID} | grep "Current Status" | grep -iE "Done|Cancelled|Cleared|Aborted"`
done

# check if another job is generating a proxy...
while [ -f /tmp/gLiteProxyLocked_${USER} ]
 do
   sleep 10
 done

# set lock...
touch /tmp/gLiteProxyLocked_${USER}

# create new proxy cert for 1 hours...
echo ${CERT_PASSWD} | voms-proxy-init -voms ${VOMS} -valid 01:00 -pwstdin -q &> /dev/null

# retrieve the output now...
glite-wms-job-output --dir ./output-files ${JOB_ID} &> /dev/null

# remove lock...
rm -rf /tmp/gLiteProxyLocked_${USER}

# send back the output to LGI server...
cp ./output-files/LGI_output ./LGI_output &> /dev/null

# and we are finished...
touch ./finished
