#!/bin/bash

# some settings...
export VOMS="ncf"
export X509_USER_PROXY=./x509_proxy_cert

# create job script...
cat > hello.submitted.sh << EOF_SCRIPT
export HOST=\`hostname -f\`
export DATE=\`date\`
export INPUT=\`cat LGI_input\`
echo Hello_World_GLITE from \${HOST} at \${DATE} with input: \${INPUT} ...
EOF_SCRIPT

# create JDL for this job script...
cat > hello.submitted.jdl << EOF_JDL
type = "Job";
jobtype = "Normal";
executable = "/bin/bash";
arguments = "hello.submitted.sh";
stdoutput = "LGI_output";
stderror = "stderr";
outputsandbox = { "LGI_output", "stderr" };
inputsandbox = { "hello.submitted.sh", "LGI_input" };
shallowretrycount = 3;
requirements = ( other.gluecepolicymaxcputime > 720 );
myproxyserver = "px.grid.sara.nl";
EOF_JDL

# create and submit new job from JDL...
export RUNNING=""
while [ "${RUNNING}" == "" ]
do
 myproxy-init -s px.grid.sara.nl -d -n > /dev/null
 voms-proxy-init -voms ${VOMS} -valid 196:00 -q &> /dev/null
 glite-wms-job-submit -a -o ${HOME}/my-glite-jobs hello.submitted.jdl | grep https | grep 9000 | tail -1 &> ./running
 export RUNNING=`cat ./running | grep -E '^https'`
 if [ "${RUNNING}" == "" ]
 then
    sleep 300
 fi
done

# wait until job is finished, sleep a bit...
export JOB_STATE=""
while [ "${JOB_STATE}" == "" ]
do
    sleep 300
    export JOB_ID=`cat ./running`
    export OUTPUT=`glite-wms-job-status ${JOB_ID} 2>&1`
    export JOB_STATE=`echo ${OUTPUT} | grep "Current Status" | grep -iE "Done|Cancelled|Cleared|Aborted"`
    export FAILED=`echo ${OUTPUT} | grep -i "expired"`
    if [ "${FAILED}" != "" ]
    then
      voms-proxy-init -voms ${VOMS} -valid 196:00 -q &> /dev/null 
    fi
done

# retrieve the output now...
glite-wms-job-output --dir ./output-files ${JOB_ID} &> /dev/null

# send back the output to LGI server...
cp ./output-files/*/LGI_output ./LGI_output &> /dev/null

# and we are finished...
touch ./finished
