#!/bin/sh
/bin/touch running
/bin/sleep 10
echo -n "Hello_World from " > LGI_output
/bin/sleep 10
/bin/cat LGI_target_resources >> LGI_output
/bin/sleep 10
echo -n " submitted from " >> LGI_output
/bin/sleep 10
/bin/cat LGI_input >> LGI_output
/bin/sleep 10
/bin/touch finished
/bin/rm running
