#!/bin/bash
export LGI_ROOT=${HOME}/LGI/daemon
export OLD_ROOT=`pwd`

if [ -f ${LGI_ROOT}/LGI.pid ]
then

 PID=`tail -n1 ${LGI_ROOT}/LGI.pid`
 SPID=`ps -p ${PID} -o pid=`

 if [ "${SPID}" == "" ]
 then
    DATE=`date`
    echo "At ${DATE} the LGI daemon was not running anymore, restarting..."
    if [ -f ${LGI_ROOT}/LGI.log ]
    then
       DATE=`date +%s`
       mv ${LGI_ROOT}/LGI.log ${LGI_ROOT}/LGI.log_${DATE}
    fi
    cd ${LGI_ROOT}; ${LGI_ROOT}/bin/LGI_daemon -d -l ${LGI_ROOT}/LGI.log ${LGI_ROOT}/LGI.cfg; cd ${OLD_ROOT}
    ps -C LGI_daemon -o pid=,user | grep ${USER} | awk '{ print $1 }' > ${LGI_ROOT}/LGI.pid
 fi

else

 echo No LGI.pid found, starting the daemon...
 cd ${LGI_ROOT}; ${LGI_ROOT}/bin/LGI_daemon -d -l ${LGI_ROOT}/LGI.log ${LGI_ROOT}/LGI.cfg; cd ${OLD_ROOT}
 ps -C LGI_daemon -o pid=,user | grep ${USER} | awk '{ print $1 }' > ${LGI_ROOT}/LGI.pid

fi
