#!/bin/bash
export LGI_ROOT=${HOME}/temp/LGI/daemon

. ${HOME}/.profile > /dev/null

if [ -f ${LGI_ROOT}/LGI.pid ]
then

 PID=`tail -n1 ${LGI_ROOT}/LGI.pid`
 SPID=`ps -p ${PID} -o pid=`

 if [ "${SPID}" == "" ]
 then
    DATE=`date`
    echo "At ${DATE} the LGI daemon was not running anymore, restarting..."
    if [ -f ${LGI_ROOT}/LGI.log ]
    then
       DATE=`date +%s`
       mv ${LGI_ROOT}/LGI.log ${LGI_ROOT}/LGI.log_${DATE}
    fi
    ${LGI_ROOT}/bin/LGI_daemon -d -l ${LGI_ROOT}/LGI.log ${LGI_ROOT}/LGI.cfg
    ps -C LGI_daemon -o pid= | tail -n1 > ${LGI_ROOT}/LGI.pid
 fi

else

 echo No LGI.pid found, starting the daemon...
 ${LGI_ROOT}/bin/LGI_daemon -d -l ${LGI_ROOT}/LGI.log ${LGI_ROOT}/LGI.cfg
 ps -C LGI_daemon -o pid= | tail -n1 > ${LGI_ROOT}/LGI.pid

fi
