#!/bin/sh
export LGI_ROOT=/var/www/html/LGI/daemon

if [ -f ${LGI_ROOT}/LGI.pid ]
then

 PID=`tail -n1 ${LGI_ROOT}/LGI.pid`
 SPID=`ps -p ${PID} -o pid=`

 echo Checking for PID ${PID}...
 if [ "${SPID}" == "" ]
 then
    echo "LGI daemon not running anymore, restarting..."
    if [ -f ${LGI_ROOT}/LGI.log ]
    then
       DATE=`date +%s`
       mv ${LGI_ROOT}/LGI.log ${LGI_ROOT}/LGI.log_${DATE}
    fi
    ${LGI_ROOT}/bin/LGI_daemon -d -l ${LGI_ROOT}/LGI.log ${LGI_ROOT}/LGI.cfg
    ps -C LGI_daemon -o pid= | tail -n1 > ${LGI_ROOT}/LGI.pid
 else
    echo "LGI daemon still running..."
 fi

else

 echo No LGI.pid found, starting the daemon...
 ${LGI_ROOT}/bin/LGI_daemon -d -l ${LGI_ROOT}/LGI.log ${LGI_ROOT}/LGI.cfg
 ps -C LGI_daemon -o pid= | tail -n1 > ${LGI_ROOT}/LGI.pid

fi
