#!/usr/bin/php -q
<?php

$workunitid = file_get_contents( "running" );
if( $workunitid === FALSE ) exit( 1 );
$workunitid = intval( $workunitid );

$LGI_DIR = getcwd();

chdir( "/home/boinc/Classical/html/user" );

include_once( "../inc/db.inc" );
include_once( "../inc/util.inc" );

db_init();

chdir( $LGI_DIR );

$workunit = mysql_query( "SELECT * FROM workunit WHERE id=$workunitid" );
if( !mysql_num_rows( $workunit ) ) exit( 1 );
$workunit = mysql_fetch_object( $workunit );

if( $workunit -> canonical_resultid || $workunit -> error_mask ) exit( 1 );

exit( 0 );
?>
