#!/bin/sh

cat > ./llsubmit_script << END_OF_LLSUBMIT_SCRIPT
#@ shell = /bin/sh
#@ job_name = hello_world_ll
#@ job_type = serial
#@ node_usage = shared
#@ notification = never
# # @ node = 1
# # @ tasks_per_node = 1
#@ output = LGI_output
#@ wall_clock_limit = 00:15:00
#@ queue

sleep 10
echo -n "Hello_World_LL running on nodes \${LOADL_PROCESSOR_LIST} in directory \${LOADL_STEP_INITDIR} at " 
sleep 20
cat \${LOADL_STEP_INITDIR}/LGI_target_resources
sleep 40
echo -n ". This job was submitted with input: "
sleep 80
cat \${LOADL_STEP_INITDIR}/LGI_input
sleep 160
echo "."

touch \${LOADL_STEP_INITDIR}/finished

END_OF_LLSUBMIT_SCRIPT

llsubmit llsubmit_script | awk '/submitted/ { print $4 }' | cut -d'.' -f5 | cut -d '"' -f1 > ./running
