#!/bin/sh
if [ -f running ]
then
 ID=`cat running`
 FINISHED=`llq $ID | grep $ID`
 if [ "$FINISHED" == "" ]
 then
  if [ -f aborted ]
  then
   exit 0
  fi
  if [ -f finished ]
  then
   exit 0
  else
   exit 1
  fi
 else
  exit 1
 fi
else
 exit 1
fi
