#!/bin/sh
if [ -f running ]
then
 ID=`/bin/cat running`
 FINISHED=`llq $ID  | /usr/bin/grep $ID`
 if [ "$FINISHED" == "" ]
 then
  if [ -f aborted ]
  then
#   echo Aborted
   exit 0
  fi
  if [ -f finished ]
  then
#   echo Finished
   exit 1
  else
#   echo Crashed
   exit 1
  fi
 else
#  echo Running and aborting now
  llcancel $ID
  /usr/bin/touch aborted
  exit 1
 fi
else
# echo Not started yet
 exit 1
fi
