#!/bin/sh

if [ "$2" == "" ]
then
 echo "UpdateDB query servers [mysql options]"
 exit 1
fi

export QUERY=$1
export SERVERS=$2
export ESCAPEDQUERY=`echo "${QUERY}" | sed "s/'/\\\\\'/g"`
export UPDATEQUERY="INSERT INTO updates SET servers='${SERVERS}', update_query='${ESCAPEDQUERY}'"

shift
shift

echo "Running an update cycle..."
#php -f ./cron_job.php

echo "Applying query \"${QUERY}\"..."
echo "${QUERY}" | mysql $@
echo "${UPDATEQUERY}" | mysql $@

