#!/bin/bash

# some settings...
export CERT_PASSWD="m@rks0m3rs007"
export VOMS="ncf"
export X509_USER_PROXY=./x509_proxy_cert
export LGI_DIR="${HOME}/LGI"

# register at myproxy px.grid.sara.nl...
echo ${CERT_PASSWD} | myproxy-init -s px.grid.sara.nl -d -n -S > /dev/null

# create new proxy cert for 196 hours...
echo ${CERT_PASSWD} | voms-proxy-init -voms ${VOMS} -valid 196:00 -pwstdin -q &> /dev/null

# create job script...
cat > nonmem.submitted.sh << EOF_SCRIPT
mkdir -p NONMEM_6.2.0/UNIX
cp NONMEMVI.tar NONMEM_6.2.0/UNIX
sh ./SETUP ./ ./ `which f77` -O `which ar` IEEE
sh ./run/nmfe6 input.nonmem output.nonmem
EOF_SCRIPT

# create JDL for this job script...
cat > nonmem.submitted.jdl << EOF_JDL
type = "Job";
jobtype = "Normal";
executable = "/bin/bash";
arguments = "nonmem.submitted.sh";
stdoutput = "stdout";
stderror = "stderr";
outputsandbox = { "output.nonmem", "stdout", "stderr" };
inputsandbox = { "nonmem.submitted.sh", "input.nonmem", "NONMEMVI.tar", "SETUP" };
shallowretrycount = 3;
requirements = ( other.glueceinfototalcpus >= 1 && other.gluecepolicymaxcputime > 30 );
myproxyserver = "px.grid.sara.nl";
EOF_JDL

# convert input...
cp LGI_input input.nonmem; dos2unix input.nonmem

# get other input files...
cp ${LGI_DIR}/daemon/NONMEM/NONMEMVI.tar .
cp ${LGI_DIR}/daemon/NONMEM/SETUP .

# create and submit new job from JDL...
glite-wms-job-submit -a -o ${HOME}/my-glite-jobs nonmem.submitted.jdl | grep https | tail -1 &> ./running

# wait until job is finished, sleep a bit...
export JOB_STATE=""
while [ "${JOB_STATE}" == "" ]
do
    sleep 300
    export JOB_ID=`cat ./running`
    export JOB_STATE=`glite-wms-job-status ${JOB_ID} | grep "Current Status" | grep -iE "Done|Cancelled|Cleared|Aborted"`
done

# retrieve the output now...
glite-wms-job-output --dir ./output-files ${JOB_ID} &> /dev/null

# send back the output to LGI server...
cp ./output-files/output.nonmem ./LGI_output &> /dev/null

# and we are finished...
touch ./finished
